# Generated by Django 4.2 on 2024-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor')], max_length=50, verbose_name='role'),
        ),
    ]
