# Generated by Django 4.2 on 2024-07-18 06:34

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.file_path_image, verbose_name='Course Image'),
        ),
    ]
